export const SEND_EMAIL_CONTACT = "SEND_EMAIL_CONTACT";
export const GET_GENRE = "GET_GENRE";
export const GET_GENRES = "GET_GENRES";
export const CLEAN_GENRE = "CLEAN_GENRE";
export const GET_ARTISTS = "GET_ARTISTS";
export const GET_PLAYLIST = "GET_PLAYLIST";
export const GET_USER_DATA = "GET_USER_DATA";
export const GET_SEARCH = "GET_SEARCH";
export const GET_ARTIST_SONG_SEARCH = "GET_ARTIST_SONG_SEARCH";
export const GET_ARTIST_DATA = "GET_ARTIST_DATA";
export const GET_ARTIST_ALBUM = "GET_ARTIST_ALBUM";
export const GET_ARTIST_SONGS = "GET_ARTIST_SONGS";
export const GET_ARTIST_TOP = "GET_ARTIST_TOP";
export const GET_RES_REVIEWS = "GET_RES_REVIEWS"; //resource reviews (artist, album, song)
export const GET_ALBUM_DATA = "GET_ALBUM_DATA";
export const GET_ALBUM_SONGS = "GET_ALBUM_SONGS";
export const GET_ALL_REVIEWS = "GET_ALL_REVIEWS";
// Actions de la DB ---------------------------------
export const GET_RANDOM_SONGS = "GET_RANDOM_SONGS";
export const GET_TOP_SONGS = "GET_TOP_SONGS";
export const GET_RANDOM_ARTISTS = "GET_RANDOM_ARTISTS";
export const GET_TOP_ARTISTS = "GET_TOP_ARTISTS";
export const CREATE_DB_ALBUMS = "CREATE_DB_ALBUMS";
export const CREATE_DB_GENRES = "CREATE_DB_GENRES";
export const GET_DB_ALBUMS = "GET_DB_ALBUMS";
//---------------------------------------------------
export const GET_SONG_DATA = "GET_SONG_DATA";
export const GET_ALL_USERS="GET_ALL_USERS";
export const GET_GENRE_ALBUM = "GET_GENRE_ALBUM";
export const ON_PAGE_CHANGED ="ON_PAGE_CHANGED";
export const CALC_PAGES="CALC_PAGES";
export const GET_RANDOM_FEED="GET_RANDOM_FEED";
export const GET_OTHER_USER_DATA="GET_OTHER_USER_DATA";
export const GET_USER_SEARCH="GET_USER_SEARCH";
export const SET_PRICE="SET_PRICE";
export const CLEAR_ARTIST="CLEAR_ARTIST";
export const CLEAR_SONG="CLEAR_SONG";
export const CLEAR_ALBUM="CLEAR_ALBUM";
