export const SEND_EMAIL_CONTACT = "SEND_EMAIL_CONTACT";
export const GET_GENRE = "GET_GENRE";
export const GET_GENRES = "GET_GENRES";
export const CLEAN_GENRE = "CLEAN_GENRE";
export const GET_ARTISTS = "GET_ARTISTS";
export const GET_PLAYLIST = "GET_PLAYLIST";
export const GET_USER_DATA = "GET_USER_DATA";
export const GET_SEARCH = "GET_SEARCH";
export const GET_ARTIST_DATA = "GET_ARTIST_DATA";
export const GET_ARTIST_TOP = "GET_ARTIST_TOP";
export const GET_RES_REVIEWS = "GET_RES_REVIEWS"; //resource reviews (artist, album, song)
export const GET_ALBUM_DATA = "GET_ALBUM_DATA";
export const GET_ALBUM_SONGS = "GET_ALBUM_SONGS";
