export const SEND_EMAIL_CONTACT = 'SEND_EMAIL_CONTACT';

export const GET_USER_DATA = "GET_USER_DATA"

// CONSTANTS PLAYER
export const GET_GENRE = 'GET_GENRE';
export const GET_GENRES = 'GET_GENRES';
export const CLEAN_GENRE = 'CLEAN_GENRE';
export const GET_ARTISTS = 'GET_ARTISTS';
export const GET_PLAYLIST = 'GET_PLAYLIST';